language: node_js
node_js:
    - 7
sudo: false
cache:
before_install:
  - pip install --user RangeHTTPServer
install:
  - npm install
before_script:
  - python -m RangeHTTPServer &
script:
  - phantomjs test/run-jasmine.js http://localhost:8000/test/
